### ISSUE TITLE
Skip between part number and name missing, if grid layout is used

### ISSUE THREAD

**Issue by vrilcode** [Omikhleia/resilient.sile#49]
When I use grid layout and set grid spacing slightly larger than font size, skip between part number and name is missing:
<img width="159" alt="image" src="https://github.com/Omikhleia/resilient.sile/assets/31141078/d5f0c891-2ba6-4053-9e53-28937908a3e8">

Without grid layout (or spacing = 11pt):
<img width="156" alt="image" src="https://github.com/Omikhleia/resilient.sile/assets/31141078/21c688bc-88fd-43ca-b31d-b65e5262a93a">

Please look at my minimal example (output PDF file attached):
```
\begin[papersize=a5,class=resilient.book]{document}
\use[module=packages.lorem]
\use[module=packages.grid]
\grid[spacing=13pt]
\font[family=Libertinus Serif,size=11pt]

\part{Name Of Part One}
\chapter{Chapter One}
\lorem

\end{document}
```
[test.pdf](https://github.com/Omikhleia/resilient.sile/files/11523640/test.pdf)

**Comment by Omikhleia** [comment]
There's no skip between the part number and the part name, just a line break: the vertical spacing is thus that of a (regular) baseline...
In grid mode, the baseline is aligned on the grid (so at 13pt in your case), but each line here being bigger than that, they look very close. Conversely, on the chapter, there's a descender (the -p-) that causes the grid logic to skip a grid line... and then we get a very large line break. See by yourself, adding `\grid:debug` after it being set:

![image](https://github.com/Omikhleia/resilient.sile/assets/18075640/7a8ff264-0956-4175-b5a2-5c4c40b3eef3)

They are both kind of ugly ^^
I'm afraid that's how grid mode currently works, however. I have no idea what would be expected for such things - I am not sure what the typographical approach to "big" titles in grid mode should be.

TBH, I don't know why so many people want to use grid typesetting, a need that came from Bibles, which probably do not have that kind of parts and chapters anyway...

So perhaps it's the wrong tool for generic formatting. The question is not specific to the resilient classes, though, and there's probably little I can do here. I would have suggested to use different grids at places, but this does not seem to even work.

**Comment by Omikhleia** [comment]
Oh, and with spacing to 11pt, the ascenders (expecially the -f-) likely plays a role:

![image](https://github.com/Omikhleia/resilient.sile/assets/18075640/3ca7abea-7170-45c2-8556-0b5bee3ef2ae)

It seems to me the grid logic is far too naive to work well...

**Comment by vrilcode** [comment]
Thanks for explanation! I will ask in SILE discussions.

> I'm afraid that's how grid mode currently works, however. I have no idea what would be expected for such things - I am not sure what the typographical approach to "big" titles in grid mode should be.

I would expect, that everything, which is not a regular paragraph should only start on a grid line - so only the first line has to be on the grid (maybe this is different at the beginning of a page). At least, this is a very common solution for grid typesetting.

> TBH, I don't know why so many people want to use grid typesetting, a need that came from Bibles, which probably do not have that kind of parts and chapters anyway...

I think it's mostly a design issue (apart from improved legibility, especially on thin paper and with multiple columns). I also hardly know any "ordinary" books from professional publishers that do not typeset in grid.

**Comment by Omikhleia** [comment]
> I also hardly know any "ordinary" books from professional publishers that do not typeset in grid.

Really? I don't see true grid typesetting in most of the books I own. Fixed line height, sure, and adequate vertical skips, but that's a slightly different thing.

**Comment by vrilcode** [comment]
> Really? I don't see true grid typesetting in most of the books I own. Fixed line height, sure, and adequate vertical skips, but that's a slightly different thing.

Yes. It is easy to check by holding a book page up to the light. I own about 300 books and even smaller publishers set everything in grid. Only books, which have a lot of changing font sizes in paragraphs or a lot of different elements, tend to have no grid (for instance O'Reilly books). Nearly all of my books are in German. So I thought, that's maybe a German thing. But now I checked also my few English books (US/UK) and most of them have it (they are more from academic publishers). Only a book about LaTeX doesn't have it, but it was also produced with LaTeX :D

**Comment by jslabovitz** [comment]
I’ve designed about 20 books over as many years, and I think every one of them ended up having a baseline grid. These were largely with InDesign, and there were reasons related to InDesign's "paste-up" metaphor that made using a baseline grid the easiest way to solve alignment problems. But in my experience learning traditional typesetting in general, it's always been seen to be best to have lines "backed up" against each other on the page, whether through algorithms (baseline grids) or hand-calculated linespacing/leading.

As @vrilcode mentioned, most modern book typesetting seems to be done on a grid, or at least on a fairly predictable linespacing system. TeX-derived systems seem to be an anomaly here, along with (probably) troff, which I know from experience was the system of choice at O'Reilly for a while. (I used to work there.)

For my own work, I typically determine the baseline grid first, based on the needs of the work, *then* the spacing/alignment of heads, etc. It just makes everything come together much nicer — and is far easier than trying to do the math to make sure all the different linespacing and before/after spacing work out properly. When I initially came to SILE, having a properly implemented baseline grid was an important feature for me. Although I'm following the project, one of the primary reasons I'm not using SILE regularly is because the function doesn't work reliably. (As you may recall, I filed several issues related to the feature not working as I expected.)

So here's a vote for making it work properly.

**Comment by vrilcode** [comment]
Hi @jslabovitz, may I ask what you currently use for your work? Still InDesign?

An open source typesetting system that reliably masters grids would really have a unique selling point. For those who don't need grid typesetting, I think there's LaTeX anyway, where the ecosystem will always be superior.

**Comment by Omikhleia** [comment]
> It is easy to check by holding a book page up to the light
> (...)
> most modern book typesetting seems to be done on a grid, or at least on a fairly predictable linespacing system. 

Folks, I really don't think we are discussing the same things or types of books, now :) :smiley_cat: 

No visible grid:

![image](https://github.com/Omikhleia/resilient.sile/assets/18075640/1a8e0711-40d9-4a5e-a264-a11b16c11d96)

Some sort of grid, by sections are off-grid, and compensated by the skips:

![image](https://github.com/Omikhleia/resilient.sile/assets/18075640/92a96c33-e8d5-4a53-8d16-35f109b923c1)

No visible grid either:

![image](https://github.com/Omikhleia/resilient.sile/assets/18075640/86361266-335a-471e-ae65-f1fd8722c5bd)

(My playing with just a few random scholarly / academic books from established _literature_ publishers -- Books with footnotes, sections, figures, lots of quotations, etc.)

I don't even know what "TeX-derived systems seem to be an anomaly here" may imply here: There are _even_ existing solutions for (La)TeX and grids (e.g. https://ctan.gutenberg-asso.fr/macros/latex/contrib/grid/grid.pdf)... Yup, with multiple-columns and back-and-forth switching between single-column and two-column content...

This being said, I am not fully disagreeing -- But this is not an obvious matter at all! And I don't know what a "vote" would mean, nor a "selling point" for an open source software, which needs way more knowledgeable developers to achieve anything in that direction. But anyway, this is not the right place for this discussion.

**Comment by vrilcode** [comment]
> There are even existing solutions for (La)TeX and grids ...

But they don't really work or only in very specific scenarios.

> ... nor a "selling point" for an open source software

Sorry, it was maybe the wrong word (I am not a native speaker). I would rather call it a "unique feature" (among other open source tools).

> ... this is not the right place for this discussion.

Agreed :)
